### ISSUE TITLE
Corpora in format for other systems

### ISSUE THREAD

**Issue by mermolenko** [sebischair/NLU-Evaluation-Corpora#2]
Hi, could you please provide corpora in format you were using to test other systems. Depending on the way you convert data results may be different.

**Comment by DaBr01** [comment]
Since the corpora are meant to be applicable universally, we choose a data format which is not bound to a single service. But we will provide the Python scripts which we used to conduct the evaluation. They will handle the conversion for the evaluated NLU services.

Independent from that, for each service (except for Rasa), there is just one admissible data format and hence just one possible (right) conversion. Therefore I don't see how results could differ (except if the conversion introduces errors, which will of course result in a different outcome).
